url: https://www.place-emploi-public.gouv.fr/
api_path: https://www.place-emploi-public.gouv.fr/ajax-min.php
parser_parameters:
  title : //li/div[2]/a[1]/span[2]
  employer : //li/div[3]/span[1]
  topic : //li//div[4]/span[1]
  localization : //li/div[5]/span[1]
  affiliate : //li/div[6]/span[1]
  date : //li/div[7]/span[1]
  url : //li/div[2]/a[1]/@href
time_sleep: 0.6
max_offset: 205
columns_need_correction:
  - date
  - employer
  - title
  - topic
corrections:
  - '\n                '
  - '            '
  - '\n'
